version: '2'

services:
  athena:
    environment:
      - CONNECTION_STRING=abc
    image: athena:v2
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ../env:/home/athena/env
    container_name: athena_v2
