version: '2'
services:
  peer-proxy:
    build:
      context: ./
      dockerfile: ./docker/proxy/grpcwebproxy/peer/Dockerfile
    image: grpcwebproxy:peer
    ports:
      - "8080:8080"
      - "8443:8443"
  orderer-proxy:
    build:
      context: ./
      dockerfile: ./docker/proxy/grpcwebproxy/orderer/Dockerfile
    image: grpcwebproxy:orderer
    ports:
      - "8081:8081"
      - "8444:8444"
  configtxlator:
    build:
      context: ./
      dockerfile: ./docker/configtxlator/Dockerfile
    image: configtxlator
    ports:
      - "8083:8083"
